### list all messages

GET http://localhost:3000/messages

### create a new mwssage
POST http://localhost:3000/messages
content-type: application/json

{
    "content" : "Message after adding DI"
}

### Get an individual mesasage
GET http://localhost:3000/messages/331